### ISSUE TITLE
TODO for first draft of Phase 1 paper.

### ISSUE THREAD

**Issue by samuelklee** [broadinstitute/lrma-aou1-panel-creation#52]
@hangsuUNC Run HiPhase on whole genome using current parameters with no filtering for all samples:
- [ ] Break out a per-sample workflow from the current PhysicalAndStatisticalPhasing workflow. This should not scatter over samples in the workflow itself; rather, scatter at the Terra level (seems to scale better with Job Manager, easier to test on a few samples).
- [ ] Run on HPRC+AoU1 and attach per-sample short + SV HiPhase outputs to the data model.
- [ ] Create short + SV HiPhase merged VCFs and place in a documented location in the workspace bucket.
- [ ] Lower priority: refactor PhysicalAndStatisticalPhasing to call into the broken-out per-sample workflow.

@samuelklee Experiment with reducing short-variant count for Shapeit4 while maintaining SV imputation performance (Iris is focusing on AF > 0.05 for eQTL analyses):
- [ ] Finish chr6 evaluation, currently running with 10kb windows and AF >= 0.02. This is still using the old unsharded version of the Shapeit4 workflow.
- [ ] Incorporate windowing and AF filtering into sharded Shapeit4 workflow.
- [ ] Rerun sharded workflow on chr6 to verify performance.

Statistical phasing:

- [ ] @hangsuUNC Break out and run sharded Shapeit4 workflow with windows/filters on whole genome.
- [ ] Lower priority: refactor PhysicalAndStatisticalPhasing to call into the broken-out sharded Shapeit4 workflow.

Main figure: 
- [ ] @samuelklee Create leave-out-all-HPRC  KAGE+GLIMPSE panel and run evaluation.
- [ ] a) summary statistics of 40 HPRC-in-1kGP samples, comparing numbers of SV insertions/deletions across: 1) HPRC assemblies, 2) 8x LR, 3) imputed SR (vs. leave-out-all-HPRC panel), 4) GATK-SV SR. Stratify by region type as minimally as possible. Perhaps only include common?
- [ ] b) precision and recall metrics vs. HPRC dipcall truth: 1) 8x LR, 2) imputed SR (vs. leave-out-all-HPRC panel), 3) GATK-SV SR. Same region/frequency stratification/cutoff.

Generate inputs for eQTL:

- [ ] @samuelklee Create KAGE+GLIMPSE panel.
- [ ] @samuelklee Impute full panel into 731 MAGE samples.

Supplementary figures: 
- [ ] Expanded versions of main figures, with additional SV length, population, and AF stratification. Perhaps include short variants? If we slim down on short variants, ideally precision is still high but recall may be low vs. HPRC dipcall.

@kvg anything missing?

**Comment by samuelklee** [comment]
Thanks for the update! Two things:

1) Note that one flaw of the cost-estimation script is that it doesn’t actually give the real cost. It doesn’t account for preemption and cost rates for various resources are provided as fixed parameters. But hopefully we can roughly trust the distribution it reports.

2) If so, this suggests that with the per-sample view, at best we can hope for about a 50-50 split between subsetting and HiPhase. This means we will end up paying at least $500 just to subset the joint VCF! Surely a `bcftools split` strategy can beat that?

**Comment by samuelklee** [comment]
Will add notes on submissions here:

40 GATK-SV HPRC vs. dipcall, 1 sample failing w/ realign flags: https://console.cloud.google.com/storage/browser/fc-secure-e40fde7a-3e79-412c-b7ba-0c7b051badb0/submissions/5aa1a8f0-8235-4e39-b11f-85266bc02bde

**Comment by samuelklee** [comment]
Given maintained accuracy seen in https://github.com/broadinstitute/lrma-aou1-panel-creation/issues/38#issuecomment-239236454, we can proceed with a sharded run with AF>=0.01 + 10kb SV windowing over all of chr6.

To determine more appropriate shards, we can use a run linked in that comment, for which we only ran 2 manually specified 10Mb Shapeit4 shards: https://app.terra.bio/#workspaces/allofus-drc-wgs-lr-prod/AoU_DRC_WGS_LongReads_PacBio%20PAPER%20COPY/job_history/6e2c5ed2-a102-466e-9dbc-8eae7bae1021

This run contains an filtered+windowed+FilterAndConcat VCF over all of chr6, not just the 2 10Mb shards, which is the input to Shapeit4: `gs://fc-secure-8e5a6fd7-16ae-4796-80ed-8f0463af5ff1/submissions/6e2c5ed2-a102-466e-9dbc-8eae7bae1021/PhasedPanelEvaluation/bf009a41-e06b-446e-a62b-03373f65dc8c/call-FilterAndConcatVcfs/HPRCAOU.chr6.filter_and_concat.vcf.gz`

We can use the GLIMPSE1 chunk tool on this VCF to generate better shards than our naive 10Mb shards:

```
./GLIMPSE_chunk_static -I HPRCAOU.chr6.filter_and_concat.vcf.gz --region chr6 --window-size 10000000 --buffer-size 500000 -O chr6.chunks.tsv

[GLIMPSE] Split chromosomes into chunks
  * Author        : Simone RUBINACCI & Olivier DELANEAU, University of Lausanne
  * Contact       : simone.rubinacci@unil.ch & olivier.delaneau@unil.ch
  * Version       : 1.1.1
  * Run date      : 03/10/2024 - 20:59:14

Files:
  * Input VCF      : [HPRCAOU.chr6.filter_and_concat.vcf.gz]
  * Chromosome     : [chr6]
  * Output file    : [chr6.chunks.tsv]

Parameters:
  * Seed             : 15052011
  * #Threads   : 1
  * Min. Window size : 10000000bp / 1000 variants
  * Min. Buffer size : 500000bp / 100 variants

Reading input files
  * Main      : [HPRCAOU.chr6.filter_and_concat.vcf.gz]
  * #variants = 1009520 (385.52s)

Splitting data into chunks and writting to [chr6.chunks.tsv]
  * Internal window [chr6:72241-170744989] / L=170672749bp / C=1009520
  * Internal window [chr6:72241-78630557] / L=78558317bp / C=504761
  * Internal window [chr6:72241-32641877] / L=32569637bp / C=252381
  * Terminal window [0] -buffer:[chr6:72241-19099133] / +buffer:[chr6:72241-19599242] / L=19026893bp / C=126191
  * Terminal window [1] -buffer:[chr6:19099170-32641877] / +buffer:[chr6:18577569-33141881] / L=13542708bp / C=126190
  * Internal window [chr6:32641878-78630557] / L=45988680bp / C=252380
  * Internal window [chr6:32641878-54941581] / L=22299704bp / C=126191
  * Terminal window [2] -buffer:[chr6:32641878-42755864] / +buffer:[chr6:32070923-43280008] / L=10113987bp / C=63096
  * Terminal window [3] -buffer:[chr6:42755911-54941581] / +buffer:[chr6:42255897-55441622] / L=12185671bp / C=63095
  * Internal window [chr6:54941691-78630557] / L=23688867bp / C=126189
  * Terminal window [4] -buffer:[chr6:54941691-67331114] / +buffer:[chr6:54441197-67831170] / L=12389424bp / C=63095
  * Terminal window [5] -buffer:[chr6:67331412-78630557] / +buffer:[chr6:66796360-79162564] / L=11299146bp / C=63094
  * Internal window [chr6:78630635-170744989] / L=92114355bp / C=504759
  * Internal window [chr6:78630635-132352709] / L=53722075bp / C=252380
  * Internal window [chr6:78630635-104071527] / L=25440893bp / C=126191
  * Terminal window [6] -buffer:[chr6:78630635-91152068] / +buffer:[chr6:78130532-91652103] / L=12521434bp / C=63096
  * Terminal window [7] -buffer:[chr6:91152292-104071527] / +buffer:[chr6:90652274-104577123] / L=12919236bp / C=63095
  * Internal window [chr6:104071528-132352709] / L=28281182bp / C=126189
  * Terminal window [8] -buffer:[chr6:104071528-118372982] / +buffer:[chr6:103566858-118885012] / L=14301455bp / C=63095
  * Terminal window [9] -buffer:[chr6:118373301-132352709] / +buffer:[chr6:117873097-132988895] / L=13979409bp / C=63094
  * Internal window [chr6:132352735-170744989] / L=38392255bp / C=252379
  * Internal window [chr6:132352735-157241583] / L=24888849bp / C=126190
  * Terminal window [10] -buffer:[chr6:132352735-146564675] / +buffer:[chr6:131821158-147064995] / L=14211941bp / C=63098
  * Terminal window [11] -buffer:[chr6:146564679-157241583] / +buffer:[chr6:146055131-157741653] / L=10676905bp / C=63092
  * Terminal window [12] -buffer:[chr6:157241819-170744989] / +buffer:[chr6:156680356-170744989] / L=13503171bp / C=126189
  * #chunks = 13

Total running time = 385 seconds
```

Cutting the regions from the resulting file yields:

```
cut -f 3 chr6.chunks.tsv

chr6:72241-19599242
chr6:18577569-33141881
chr6:32070923-43280008
chr6:42255897-55441622
chr6:54441197-67831170
chr6:66796360-79162564
chr6:78130532-91652103
chr6:90652274-104577123
chr6:103566858-118885012
chr6:117873097-132988895
chr6:131821158-147064995
chr6:146055131-157741653
chr6:156680356-170744989
```

Copied to gs://fc-secure-8e5a6fd7-16ae-4796-80ed-8f0463af5ff1/scratch/slee/chr6.chunks.region.tsv.

Did this on a VM manually, we should put it into the workflow before kicking off WG. Probably doesn't make much of a difference since our panel is probably plenty dense, but it's the sort of thing you're supposed to do, so we might as well.

Kicked off the PhasedPanelEvaluationFromHiPhase workflow leaving out 40 HPRC samples here: https://app.terra.bio/#workspaces/allofus-drc-wgs-lr-prod/AoU_DRC_WGS_LongReads_PacBio%20PAPER%20COPY/job_history/913b51d5-df0b-4919-a6cb-6db485d6c1b9

If the numbers look good, we should run InputPhasedPanelEvaluation using the Shapeit4 result (which is on the full panel) here to generate the full KAGE+GLIMPSE panel, rather than the leave-out. Then we can reimpute MAGE and get feedback on whether this reduced chr6 panel with fewer short variants is acceptable for eQTLs. If so, then we can proceed to WG.

**Comment by samuelklee** [comment]
Once these runs complete, I think we have the following cohorts for comparison on 40 HPRC samples, which should provide a basis for plots of summary statistics and accuracy vs. dipcall:

- LR filter+concat (unimputed)
- LR panel (imputed)
- SR vs. full (we don't need to show this in the paper, since that's the whole point of doing leave-out)
- SR vs. leave-out-40
- SR GATK-SV

**Comment by samuelklee** [comment]
Notes for resolving GATK-SV symbolic alleles:

```
python ~/Downloads/resolve_light.py 1KGP_3202.gatksv_svtools_novelins.freeze_V3.wAF.chr6.vcf.gz /mnt/4AB658D7B658C4DB/working/ref/Homo_sapiens_assembly38.fasta | bgzip -c > 1KGP_3202.gatksv_svtools_novelins.freeze_V3.wAF.chr6.resolve_light_insseq.vcf.gz
bbcftools query -f '%CHROM\t%POS\t%ID\t%REFSEQ\t%INSSEQ\n' 1KGP_3202.gatksv_svtools_novelins.freeze_V3.wAF.chr6.resolve_light_insseq.vcf.gz  | bgzip -c > 1KGP_3202.gatksv_svtools_novelins.freeze_V3.wAF.chr6.resolve_light_insseq.annot.tsv.gz
tabix -s1 -b2 -e2 1KGP_3202.gatksv_svtools_novelins.freeze_V3.wAF.chr6.resolve_light_insseq.annot.tsv.gz
echo "##INFO=<ID=INSSEQ,Number=.,Type=String,Description=\"Sequence of insertion\">" > header.txt
echo "##INFO=<ID=REFSEQ,Number=.,Type=String,Description="Original reference sequence">" >> header.txt
bcftools annotate 1kGP_high_coverage_Illumina.chr6.filtered.SNV_INDEL_SV_phased_panel.vcf.gz -a 1KGP_3202.gatksv_svtools_novelins.freeze_V3.wAF.chr6.resolve_light_insseq.annot.tsv.gz -c CHROM,POS,~ID,REFSEQ,INSSEQ -h header.txt | bgzip -c > 1kGP_high_coverage_Illumina.chr6.filtered.SNV_INDEL_SV_phased_panel.annot.vcf.gz
```

Preliminary version of plot revealed only short-variant alleles are resolved, yielding ~10% SV recall: https://docs.google.com/presentation/d/1z5TFuvydlCBbskWCsGzLnloHJKkiF1U9AIr8RfxM1TQ/edit?usp=sharing

**Comment by samuelklee** [comment]
40 HPRC GATK-SV resolved, w/ realign flags: https://app.terra.bio/#workspaces/allofus-drc-wgs-LR-prodPaper/AoU_DRC_WGS_LongReads_Imputation/job_history/1c49dbd3-a4ea-45a6-a7a6-5cc4ee0b5b52

**Comment by samuelklee** [comment]
More preliminary figures here, showing Byrska-Bishop phased panel recall ~40% after resolving DELs and INSs as above: https://docs.google.com/presentation/d/1z5TFuvydlCBbskWCsGzLnloHJKkiF1U9AIr8RfxM1TQ/edit#slide=id.p

Currently rerunning with the MHC (chr6:28,510,120-33,480,577) masked out of the non-TR/homopolymer BED with bedtools:

- LR filter+concat (unimputed): https://app.terra.bio/#workspaces/allofus-drc-wgs-LR-prodPaper/AoU_DRC_WGS_LongReads_Imputation/job_history/9d7cb577-02ea-4962-86ac-c97c32967829
- LR panel (imputed): https://app.terra.bio/#workspaces/allofus-drc-wgs-LR-prodPaper/AoU_DRC_WGS_LongReads_Imputation/job_history/69b8bce4-2877-4470-9f6e-c1824e88f5a1
- SR vs. leave-out-40: https://app.terra.bio/#workspaces/allofus-drc-wgs-LR-prodPaper/AoU_DRC_WGS_LongReads_Imputation/job_history/c73a6547-b851-4ebd-b6c4-4e29b288fb63
- SR GATK-SV: https://app.terra.bio/#workspaces/allofus-drc-wgs-LR-prodPaper/AoU_DRC_WGS_LongReads_Imputation/job_history/14058dc2-9bf6-4c39-8008-b4b139ee0361

- LR filtered/windowed filter+concat (unimputed)
- LR filtered/windowed panel (imputed)
- SR vs. filtered/windowed leave-out-40

**Comment by hangsuUNC** [comment]
HPRC + AoU 1074 sample whole genome hiphased vcfs have been completed and pasted to the terra work table. The cost varies from 0.1-0.9$ per sample. Currently merging it to a multi-sample filtered vcfs.

**Comment by samuelklee** [comment]
Will come back and write a status update now that physical+statistical phasing is complete, but see status slide from today.

Hit a snafu when building the KAGE+GLIMPSE panel. The KAGE obgraph package didn't like a site at chr7:57336990 and threw an exception:

```
chr7	57336989	.	T	TG	.	PASS	ID=chr7-57336989-allele618843-2
chr7	57336990	.	GT	GG	.	PASS	ID=chr7-57336991-allele618845-1
```

Surprised this is the only instance in ~20M variants. Not quite sure why it's problematic, but it may have something to do with the fact that it's not atomized---in which case, not quite sure why the upstream `bcftools norm -a` in PanGeniePanelCreation didn't take care of it.
